B-AROL-O/ARNEIS

- .github/workflows/linter.yml
See https://github.com/github/super-linter
> [Feat] Add GitHub workflow: Super-Linter

- README.md
> [Fix] README.md: Remove spurious characters from URL

- LICENSE
Closes https://github.com/B-AROL-O/ARNEIS/issues/30
As the PR title says
> LICENSE: Extend Copyright year to 2022

- .github/linters/.python-black
Closes #61
Enable the "Single quotes option" feature for Black
in order to have the files generated by `sphinx-quickstart` to pass Super-Linter.
See [#61 (comment)](https://github.com/B-AROL-O/ARNEIS/issues/61#issuecomment-1016758709)
> [Fix] Enable the "Single quotes" option feature for Black

- .github/linters/.python-black
- .github/linters/.textlintrc
- .gitignore
- .vscode/settings.json
- docs/Makefile
- docs/conf.py
- docs/howto/howto-configure-arneis-readthedocs-io.md
- docs/index.rst
- docs/make.bat
Closes #29
Based on the following instructions
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html
> [Feat] Configure Sphinx for automatic document generation

- docs/howto/howto-configure-arneis-readthedocs-io.md
Closes #85
Based on the instructions provided by @alv67 in
https://github.com/B-AROL-O/ARNEIS/issues/85#issuecomment-1021455917
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>
> [Feat] Document how to enable ReadTheDocs preview for Pull Requests

- docs/architecture/arneis-spec.md
- docs/index.rst
Closes #36
Add first shot at Functional Specification document of the ARNEIS project.
> [Feat] docs/architecture: Add arneis-spec.md

- docs/howto/howto-configure-arneis-readthedocs-io.md
Closes #95
As the subject says.
> [Feat] howto-configure-arneis-readthedocs-io: Add section: Removing the Ads

- docs/howto/howto-prepare-rpi4b-for-arneis.md
- Minor install commands fixes
- Running depthai from a remote shell
> [Feat] Improve howto-prepare-rpi4b-for-arneis

- docs/howto/howto-configure-rpi-poweredup.md
Partially closes #50
Document how to install and configure the proper software on a Raspberry Pi which will be able to control  [BrickLink part bb0961c01](https://www.bricklink.com/v2/catalog/catalogitem.page?P=bb0961c01#T=C4) (we will have 2x items in LEGO Set 42100 we will receive in resolution of #7).
The comments in related issue #50 provides a few links which list the available options.
> [Feat] docs/howto: Create howto-configure-rpi-poweredup.md

- docs/index.rst
Closes #38
Implement a few improvements to https://arneis.readthedocs.io/:
> [Feat] Improve ARNEIS homepage on ReadTheDocs

- README.md
Closes # 
Embed [video of the ARNEIS conveyor](https://twitter.com/avaresi/status/1486027840533499904) on toplevel README.md
> README.md: Embed video of the Bottle Conveyor

- docs/howto/howto-create-vm-on-azure.md
- docs/index.rst
> [Feat] Add howto-create-vm-on-azure.md

- docs/howto/howto-create-vm-on-azure.md
Fixup to https://github.com/B-AROL-O/ARNEIS/pull/111
Correct the text after "-i" option to ssh
> [Fix] howto-create-vm-on-azure: Add private-key-path after option "-i" to ssh

- docs/howto/howto-configure-arneis-readthedocs-io.md
- docs/howto/howto-install-depthai-on-windows10.md
- docs/howto/howto-prepare-rpi4b-for-arneis.md
> [Fix] Normalize Titles and ToC of documents under docs/howto

- docs/howto/howto-configure-rpi-poweredup.md
- docs/howto/howto-prepare-rpi4b-for-arneis.md
Make hostname of the Raspberry Pi described in the documentation consistent.
> [Fix] Adjust RPi 4B hostname

- docs/howto/howto-prepare-rpi4b-for-arneis.md
Use a directory already in .gitignore, so we do not mess up with git
> [Fix] DepthAI: Create virtualenv under virtualenv/

- docs/howto/howto-install-k3s-for-arneis.md
Fix trivial typo in howto-install-k3s-for-arneis.md
> [Docs] howto-install-k3s-for-arneis.md: Fix typo

- README.md
- docs/index.rst
Embed [video of the ARNEIS conveyor](https://twitter.com/avaresi/status/1486027840533499904) on toplevel <https://arneis.readthedocs.io>
Fixup to #105 
**NOTE**: Merge this only AFTER
Closes # 
See:
* https://github.com/sphinx-contrib/video
* https://gist.github.com/dbrgn/2922648
> [Feat] Embed YouTube video inside ARNEIS documentation 

- README.md
> [Feat] Misc improvements to toplevel README.md

- docs/howto/howto-train-deploy-NN.md
- docs/index.rst
> Add How-To train and deploy NN 

- docs/howto/howto-train-deploy-NN.md
Add a screenshot showing the results of the NN training.
> [Feat] howto-train-deploy-NN.md: Show training results

- docs/index.rst
Closes #92
Rearrange levels of headings in the Table of Contents
Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>
> [Fix] index.rst: Rearrange ToC

- docs/bibliography.md
- docs/index.rst
Closes #92
Add a page with link to bibliography used during the development of the ARNEIS project
> [Feat] docs: Add bibliography.md

- docs/bibliography.md
> [Feat] Update docs/bibliography.md

- docs/acronyms.md
- docs/index.rst
Create a new page and list here the definitions of all the acronyms used in the ARNEIS project
> [Feat] docs: Add page with acronyms

- README.md
> Add link to /docs subfolder

- .github/linters/.gitleaks.toml
- docs/bibliography.md
> [Feat] Improve docs/bibliography.md

- docs/index.rst
Closes #75
Quick-and-dirty fix to #75
Please make sure to revert this PR as soon as modindex produces something meaningful
> [Bugfix] index.rst: Comment out :ref:`modindex`

- docs/lego-set-42100/unboxing-lego-set-42100.md
CSV exported from CAD converted by dedicated Python script
Closes #
> Complete bags 2

- docs/lego-set-42100/unboxing-lego-set-42100.md
Closes # 
Complete inventory of LEGO Set 42100 Bags no.1
> [Feat] Complete inventory of LEGO Set 42100 Bags #1

- docs/architecture/arneis-sysarch.md
> [Feat] Expand arneis-sysarch

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Feat] Verify contents of LEGO 42100 bag set 2

- docs/architecture/arneis-swarch.md
- docs/index.rst
> [Feat] First attempt at arneis-swarch.md

- .vscode/settings.json
- docs/conf.py
- docs/index.rst
- docs/lego/camera-support.md
- docs/lego/studies.md
- mocs/studies/camera-support/README.md
> [Feat] First attempt at reorganizing arneis.readthedocs.io index

- docs/conf.py
> [Fix] Troubleshoot arneis.RTD build failure

- .readthedocs.yaml
Temporary workaround for https://github.com/B-AROL-O/ARNEIS/issues/186
Closes https://github.com/B-AROL-O/ARNEIS/issues/186
> Disable PDF generation from readthedocs site

- README.md
> add Gitpod launcher

- .github/linters/.markdown-lint.yml
- docs/lego/camera-support.md
- docs/lego/studies.md
> Trying to fix the rule MD041 disabled globally

- docs/acronyms.md
- docs/architecture/arneis-spec.md
> [Feat] Expand contents of docs/acronyms.md

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Fix] Check and update BOM for Bag 3A, 3B, 3C, 3C1, 3D

- docs/bibliography.md
> [Feat] Add `Python library to interact with Move Hub...`

- README.md
The look-and-feel of the Gitpod badge was not consistent. Fixed
> [Fix] README.md: Use a consistent Gitpod badge

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Feat] Complete LEGO Set 42100 Bags 4

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Fix] Check contents of LEGO Set 42100 Bags 3D1, 3E, 3E1, 3E2, 3F

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Feat] Add contents of LEGO Set 42100 Bags #5

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Fix] unboxing-lego-set-42100.md: Remove redundant text

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Feat] Add contents of LEGO Set 42100 Bags #6

- docs/howto/howto-control-rpi-poweredup.md
> [Fix] Typo: s/Raspberrry/Raspberry/

- docs/images/Arneis_logo_.svg
Closes #24 
Let me know if you want to change something else!
> [Feat] Add .svg logo for the ARNES project

- docs/bibliography.md
- docs/howto/howto-control-rpi-poweredup.md
Closes #154
Discuss possible alternatives for interfacing an input sensor (such as a switch or a phototransistor) to the ARNEIS Edge Controller.
> Add chapter: Interfacing an input sensor

- docs/lego-set-42100/unboxing-lego-set-42100.md
> [Fix] Verify LEGO Set 42100 Bags 5

- docs/acronyms.md
- docs/howto/howto-install-k3s-for-arneis.md
> [Feat] Expand howto-install-k3s-for-arneis

- docs/bibliography.md
Expand docs/bibliography.md
-->
> [Feat] Expand bibliography

- code/lego-parts-csv2md/README.md
- code/lego-parts-csv2md/partlist-csv2md.ipynb
- code/lego-parts-csv2md/test.csv
Closes # 
Add the Python Jupyter Notebook used to convert to Markdown table the CSV BOM files as exported from _Stud.io_ CAD
> [FEAT] lego parts converter csv to md

- docs/bibliography.md
Contributes to resolution of https://github.com/B-AROL-O/ARNEIS/issues/214
> [Feat] bibliography.md: Add links for communication Raspberry Pi-LEGO

- docs/howto/howto-install-k3s-for-arneis.md
Install additional K3s Agent Nodes.
Closes #229
> [Feat] Complete the ARNEIS K3s cluster installation

- docs/acronyms.md
- docs/howto/howto-control-rpi-poweredup.md
> [Feat] Expand howto-control-rpi-poweredup

- docs/howto/howto-install-k3s-for-arneis.md
Improve readabilty of the HOWTO by reorganizing chapter and simplify wording.
> [Feat] howto-install-k3s-for-arneis: Reorganize chapters

- mocs/project/README.md
Closes #234
Fix the broken link which was introduced in #231
> README.md: Fix broken link

- code/poweredupapp-flash-move/README.md
> [Feat] poweredupapp-flash-move: Minor improvements

- docs/bibliography.md
> bibliography: Add more links about LEGO Powered Up

- .vscode/settings.json
- docs/index.rst
> docs/index.rst: Align with latest updates in toplevel README.md

- docs/index.rst
Fixup of https://github.com/B-AROL-O/ARNEIS/pull/248
It looks like reStructuredText does not understand `&reg;`.
See also: https://stackoverflow.com/questions/38924014/how-to-superscript-a-registered-trademark-in-sphinx-restructuredtext
> [Fix] index.rst: Fix the &reg; symbol

- docs/architecture/arneis-swarch.md
Expand and clarify the architecture of the ARNEIS Kubernetes cluster.
> [Feat] docs/architecture: Update arneis-swarch.md

- README.md
Update video URL as a consequence of #246
> [Feat] README.md: Embed latest ARNEIS YouTube video 

- README.md
> [Feat] README.md: Clarify License

- docs/howto/howto-install-depthai-on-rpi.md
The text seemed to assume a circular dependency which in fact does not hold.
> howto-install-depthai-on-rpi: Correct link text

- docs/bibliography.md
> [Feat] docs: Expand bibliography.md

- docs/index.rst
Closes # 
Now that the recording of OpenCV Weekly Episode 49 is on YouTube, let's feature it on the ARNEIS.RTD homepage.
> [Feat] index.rst: Embed YT video: OpenCV Weekly Webinar Ep.49

- README.md
- docs/index.rst
Change to reflect the decision made in the ARNEIS video (#151).
Blocks #282
Credits to @davmacario for pointing us out the spelling mistake. For sure he nows American English much better than the ARNEIS core team.
> README.md: Fix spelling in ARNEIS acronym definition

- docs/howto/howto-control-rpi-poweredup.md
> Comment out offending URL

- code/arneis-bottle-recognizer/main.py
Added video preview in different screen
Closes #
> [FEAT] Added video preview in different screen

- .readthedocs.yaml
Closes #191  
Tried in my Fork, and seems that now with PDF export enabled it works. Maybe something has been corrected.
> enable pdf export

- README.md
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>
Closes #
> [Fix] README.md: Update length of ARNEIS submission Video

- docs/arneis-social-media.md
- docs/index.rst
> [Feat] arneis.rtd: Add list of posts on social media

- docs/arneis-social-media.md
- docs/index.rst
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>
Closes #
> [Feat] index.rst: Refactor contents

- docs/arneis-social-media.md
Extend page "arneis-social-media"
> [Feat] arneis-social-media: Add contents

- docs/howto/howto-use-mermaid-graphic-tool.md
Creation of an HOWTO to document how to use the Mermaid graphic tool.
Fix https://github.com/B-AROL-O/ARNEIS/issues/179
> [Feat] docs: Create howto-use-mermaid-graphic-tool.md

- docs/arneis-social-media.md
> [Feat] arneis-social-media.md: New tweets and LinkedIn posts

- docs/howto/howto-testing-portenta-x8.md
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>
Closes # 
First experiences with [Arduino Portenta X8](https://www.arduino.cc/pro/hardware/product/portenta-x8)
> [Feat] docs/howto: Add howto-testing-portenta-x8.md

- docs/arneis-social-media.md
- docs/howto/howto-control-rpi-poweredup.md
> [Feat] docs/social-media-presence: Add new links

- docs/arneis-social-media.md
- docs/bibliography.md
- docs/howto/howto-testing-portenta-x8.md
> Add section: Inspect the host OS on the Portenta X8

- docs/arneis-social-media.md
> [Feat] New tweet by @gpmacario

- docs/index.rst
Closes #134 
Restructured the TOC in the index.rst, this can produce a better PDF.
> [Feat] New document hierarchy

- README.md
- docs/index.rst
Extends https://github.com/B-AROL-O/ARNEIS/pull/315
> [Feature] Call-to-vote for ARNEIS

- .github/workflows/check-links.yml
- docs/arneis-social-media.md
> [Feat] Update arneis-social-media.md

- docs/arneis-social-media.md
- docs/howto/howto-train-deploy-NN.md
> [Feat] Update arneis-social-media

- .github/linters/.gitleaks.toml
- docs/arneis-social-media.md
> arneis-social-media: New @alv67 post on LinkedIn

- docs/howto/howto-testing-portenta-x8.md
> [Feat] update-howto-portenta-x8: Managed to scan nearby BLE devices

- docs/arneis-social-media.md
> arneis-social-media: Project Status Report for dev-cw18 is out

- docs/arneis-social-media.md
> [Feat] New gpmacario tweet about latest ARNEIS Project Status Report

- docs/bibliography.md
The URL <https://git.rwth-aachen.de/mindstorms/ev3-toolbox-matlab> does not seem to be active any longer.
Remove entry from bibliography.md
Closes #337
> [Fix] bibliography.md: Remove entry with dead link

- docs/arneis-social-media.md
> [docs] Tweet about Release 1.0 of the ARNEIS project

- docs/index.rst
> Remove request for a vote from arneis.readthedocs.io

- docs/arneis-social-media.md
The link to Top 10 popular vote form is no longer valid. Replace destination URL with a direct link to the YouTube video.
> Fix link to ARNEIS project pitch at OpenCV Spatial AI Contest Top 10

- docs/howto/howto-prepare-rpi4b-for-arneis.md
> Rework section "Install git-aware-prompt"

- README.md
README.md: Update Copyright year
> README.md: Update Copyright year

- docs/conf.py
Mimic https://github.com/B-AROL-O/ARNEIS/pull/346
> docs/conf.py: Update Copyright Year

- README.md
> Correct Youtube link to ARNEIS History video

- .github/workflows/linter.yml
- docs/howto/howto-create-landing-page-netlify.md
- docs/index.rst
Add a HOWTO with a detailed walkthrough of the steps executed to create the initial version of https://baroloteam.online/
Closes #349
> howto: Create howto-create-landing-page-netlify.md

- docs/howto/howto-configure-google-analytics.md
- docs/howto/howto-create-landing-page-netlify.md
- docs/index.rst
> [FEAT]: Extend HOWTO Create a landing page on Netlify

- README.md
> [FEAT]: Embed video of 2022-03-17 OpenCV Weekly Webinar

- README.md
There was a subtle bug in the formatting of the ARNEIS acronym.
This PR is supposed to fix it.
Please compare how ARNEIS was spelled in <https://github.com/B-AROL-O/ARNEIS/blob/main/README.md> vs. the correct one at <https://github.com/B-AROL-O/ARNEIS/blob/main/docs/index.rst>
> README.md: Fix formatting of ARNEIS acronym

- docs/howto/howto-install-micropython-nano33ble.md
- docs/index.rst
> [FEAT]: howto: Add howto-install-micropython-nano33ble

- docs/arneis-social-media.md
Add date and summary to all LinkedIn posts
> [FEAT]: arneis-social-media.md: Add date and summary to all LinkedIn posts

- docs/lego-set-42100/unboxing-lego-set-42100.md
> fix: unboxing-lego-set-42100.md
